# Generated by Django 4.2.7 on 2023-11-14 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fotoPerfil',
            field=models.ImageField(upload_to='planning_travel/media/'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(upload_to='planning_travel/media/'),
        ),
    ]
