# Generated by Django 4.2.7 on 2023-11-14 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_travel', '0002_alter_cliente_fotoperfil_alter_usuario_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='url_foto',
            field=models.ImageField(upload_to='planning_travel/media/'),
        ),
    ]
