# Generated by Django 4.2.7 on 2024-02-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_travel', '0006_alter_hotel_cantidad_habitaciones'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='reportes',
            new_name='Reporte',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='fotoPerfil',
            new_name='foto_perfil',
        ),
        migrations.RenameField(
            model_name='habitacion',
            old_name='tipoHabitacion',
            new_name='tipo_habitacion',
        ),
        migrations.RenameField(
            model_name='perfilusuario',
            old_name='fotoPerfil',
            new_name='foto_perfil',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='cantidadPersonas',
            new_name='cantidad_personas',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='cantidad_habitaciones',
            field=models.IntegerField(),
        ),
    ]
