# Generated by Django 4.2.7 on 2023-11-22 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_travel', '0007_alter_cliente_fotoperfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.CharField(max_length=254),
        ),
    ]
