# Generated by Django 4.2.7 on 2023-11-15 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning_travel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='reportes',
            new_name='Reporte',
        ),
    ]
