# Generated by Django 4.2.7 on 2023-11-15 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_travel', '0005_alter_cliente_fotoperfil_alter_foto_url_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='cantidad_habitaciones',
            field=models.IntegerField(default=0),
        ),
    ]
