# Generated by Django 4.2.7 on 2023-11-13 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=254)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Comodidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_foto', models.CharField(max_length=254)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_habitacion', models.IntegerField()),
                ('ocupado', models.BooleanField()),
                ('capacidad_huesped', models.IntegerField()),
                ('tipoHabitacion', models.CharField(max_length=255)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=250)),
                ('foto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='planning_travel.foto')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('direccion', models.CharField(max_length=200)),
                ('cantidad_habitaciones', models.IntegerField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='planning_travel.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_llegada', models.DateField()),
                ('fecha_salida', models.DateField()),
                ('cantidadPersonas', models.IntegerField()),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='planning_travel.habitacion')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=254)),
                ('descripcion', models.TextField()),
                ('permisos', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=254)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.CharField(max_length=100)),
                ('rol', models.IntegerField(choices=[(1, 'Administrador'), (2, 'Despachador'), (3, 'Cliente')], default=3)),
                ('foto', models.ImageField(upload_to='fotos/')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_reserva', models.CharField(max_length=255)),
                ('fecha_realizacion', models.DateTimeField()),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='planning_travel.reserva')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='planning_travel.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='reportes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='planning_travel.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='reporteModerador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateField()),
                ('id_reporte', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='planning_travel.reportes')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='planning_travel.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Puntuacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valoracion', models.IntegerField()),
                ('id_comentario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='planning_travel.comentario')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=254, unique=True)),
                ('precio', models.IntegerField()),
                ('inventario', models.IntegerField()),
                ('fecha_creacion', models.DateField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='planning_travel.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='perfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('numero_contacto', models.CharField(max_length=15)),
                ('fotoPerfil', models.CharField(max_length=255)),
                ('id_hotel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='planning_travel.hotel')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='planning_travel.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='HotelComodidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispone', models.BooleanField()),
                ('id_comodidad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='planning_travel.comodidad')),
                ('id_hotel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='planning_travel.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='HotelCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='planning_travel.categoria')),
                ('id_hotel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='planning_travel.hotel')),
            ],
        ),
        migrations.AddField(
            model_name='habitacion',
            name='id_hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='planning_travel.hotel'),
        ),
        migrations.AddField(
            model_name='foto',
            name='id_hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='planning_travel.hotel'),
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agregado', models.DateField()),
                ('id_hotel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='planning_travel.hotel')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='planning_travel.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='comentario',
            name='id_hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='planning_travel.hotel'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='planning_travel.usuario'),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('numero_contacto', models.CharField(max_length=15)),
                ('fotoPerfil', models.CharField(max_length=255)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='planning_travel.usuario')),
            ],
        ),
    ]
